apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-config
data:
  cdn-hercules-rpa.um.es.conf: |
    <VirtualHost *:80>
    ServerAdmin admin@hercules-rpa.es
    ServerName cdn-hercules-rpa.um.es
    DocumentRoot /var/www/cdn
    <Directory /var/www/cdn>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    allow from all
    </Directory>
    </VirtualHost>


  upload.php: |   
    <?php
    $localIP = '{{ .Values.cdn.ingress_address }}';
    // Displaying the address 
    
    define("CDN_HOST",     "{{ .Values.cdn.protocol }}://" . $localIP . "/");
    $id = uniqid();
    $target_path = "./";
    //$target_path = $target_path . basename( $_FILES['file']['name']);
    $ext = pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);
    $target_path = $target_path . basename($id . '.' . $ext);
    $filename = $id . '.' . $ext;
    $url_cdn = '{{ .Values.cdn.protocol }}://' . $localIP . '/'.$filename;

    $myObj = new \stdClass();
    $myObj->source = $_FILES['file']['name'];
    $myObj->extension = $ext;
    $myObj->name = $filename;
    $myObj->target_path = $target_path;
    $myObj->size = $_FILES['file']['size'];
    $myObj->url_cdn = $url_cdn;

    $req = new \stdClass();
    $req->name = $filename;
    $req->url_cdn = $url_cdn;

    $reqJSON = json_encode($reqJSON,JSON_UNESCAPED_SLASHES);




    if(move_uploaded_file($_FILES['file']['tmp_name'], $target_path)) {
            $responseData = notifyNewFile($filename,$url_cdn);
            $myObj->id = $responseData['id'];
            $myJSON = json_encode($myObj,JSON_UNESCAPED_SLASHES);
            echo $myJSON;
    } else{
            $myObjerror->error = "there was an error uploading the file";

            $myJSONerror = json_encode($myObjerror,JSON_UNESCAPED_SLASHES);
            echo $myJSONerror;
    }


    function notifyNewFile($filename,$url_cdn){
          // The data to send to the API
          $postData = array(
                  'name' => $filename,
                  'url_cdn' => $url_cdn
          );

          // Setup cURL
          $ch = curl_init('http://{{ .Values.backend.address }}:5000/api/orchestrator/cdn/files');
          curl_setopt_array($ch, array(
                  CURLOPT_POST => TRUE,
                  CURLOPT_RETURNTRANSFER => TRUE,
                  CURLOPT_HTTPHEADER => array(
                          //'Authorization: '.$authToken,
                          'Content-Type: application/json'
                  ),
                  CURLOPT_POSTFIELDS => json_encode($postData)
          ));

          // Send the request
          $response = curl_exec($ch);

          // Check for errors
          if($response === FALSE){
                  die(curl_error($ch));
          }

          // Decode the response
          $responseData = json_decode($response, TRUE);

          // Close the cURL handler
          curl_close($ch);

          // Print the date from the response
          return $responseData;
    }
