kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-pv-claim
  labels:
    app: cassandra
spec:
  storageClassName: {{ .Values.cassandra.volumeClaim.storageClassName }}
  accessModes:
    - {{ .Values.cassandra.volumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.cassandra.volumeClaim.capacity.storage }}
