apiVersion: v1
kind: Secret
metadata:
  name: secret-rpa
type: Opaque
data:
  username_rabbit: "{{ .Values.rabbitmq.user }}"
  password_rabbit: "{{ .Values.rabbitmq.password }}"
  username_postgres: "{{ .Values.postgres.user }}"
  password_postgres: "{{ .Values.postgres.password }}"
  username_cassandra: "{{ .Values.cassandra.user }}"
  password_cassandra: "{{ .Values.cassandra.password }}"