apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: orchestrator-rpa
  ports:
    - name: flask 
      port: {{ .Values.backend.service.flask.port }}