apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: {{ .Values.backend.service.typeFlask }}
  selector:
    app: orchestrator-rpa
  ports:
    - name: flask 
      port: {{ .Values.backend.service.flask.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: repository
  labels:
    app: repository
spec:
  type: {{ .Values.backend.service.typeFtp }}
  selector:
    app: orchestrator-rpa
  ports:
    - name: ftp 
      port: {{ .Values.backend.service.ftp.port }}
