{{- if .Values.postgres.install }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: postgres-rpa
  ports: 
    - port: {{ .Values.postgres.service.tcp.port }}
{{ end }}