apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  type: {{ .Values.cassandra.service.type }}
  selector:
    app: cassandra-rpa
  ports: 
    - port: {{ .Values.cassandra.service.tcp.port }}
