apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: dashboard-rpa
  ports:
    - name: frontend 
      port: {{ .Values.frontend.service.http.port }}
