apiVersion: v1
kind: Service
metadata:
  name: cdn
  labels:
    app: cdn
spec:
  type: {{ .Values.cdn.service.type }}
  selector:
    app: cdn-rpa
  ports: 
    - port: {{ .Values.cdn.service.tcp.port }}