apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-rpa
  labels:
    app: cassandra-rpa
spec:
  selector:
    matchLabels:
      app: cassandra-rpa
  serviceName: "cassandra-rpa"
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra-rpa
    spec:
      containers:
        - name: cassandra-rpa
          image: "{{ .Values.cassandra.image.repository }}:{{ .Values.cassandra.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: {{ .Values.cassandra.user }}
            - name: CASSANDRA_PASSWORD
              value: {{ .Values.cassandra.password }}
          ports:
            - containerPort: {{ .Values.cassandra.service.tcp.port }}
              name: cassandra
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: config-pv
      volumes:
        - name: config-pv
          persistentVolumeClaim:
            claimName: cassandra-pv-claim
