apiVersion: apps/v1
# See the Prerequisites section of https://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s.
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  # Three nodes is the recommended minimum. Some features may require a majority of nodes
  # to be available.
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      #serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 10
      nodeSelector:
        # Use Linux nodes in a mixed OS kubernetes cluster.
        # Learn more at https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os
        kubernetes.io/os: linux
      containers:
      - name: rabbitmq-k8s
        image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            memory: {{ .Values.rabbitmq.resource.request.memory }}
            cpu: "{{ .Values.rabbitmq.resource.request.cpu }}"
          limits:
            memory: {{ .Values.rabbitmq.resource.limit.memory }}
            cpu: "{{ .Values.rabbitmq.resource.limit.cpu }}"
        volumeMounts:
          - name: definitions
            mountPath: /etc/rabbitmq/definitions.json
            subPath: definitions.json
          - name: rabbitmq
            mountPath: /etc/rabbitmq/rabbitmq.conf
            subPath: rabbitmq.conf
          - name: enabled-plugins
            mountPath: /etc/rabbitmq/enabled_plugins
            subPath: enabled_plugins

        # Learn more about what ports various protocols use
        # at https://www.rabbitmq.com/networking.html#ports
        ports:
          - name: http
            protocol: TCP
            containerPort: {{ .Values.rabbitmq.service.http.port }}
          - name: amqp
            protocol: TCP
            containerPort: {{ .Values.rabbitmq.service.amqp.port }}
          - name: dist
            protocol: TCP
            containerPort: {{ .Values.rabbitmq.service.dist.port }}
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "status"]
          initialDelaySeconds: 60
          # See https://www.rabbitmq.com/monitoring.html for monitoring frequency recommendations.
          periodSeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "ping"]
          initialDelaySeconds: 20
          periodSeconds: 60
          timeoutSeconds: 10
        imagePullPolicy: {{ .Values.rabbitmq.image.pullpolicy }}
        env:
          - name: RABBITMQ-HERCULES
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE-HERCULES-RPA
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          # See a note on cluster_formation.k8s.address_type in the config file section
          - name: K8S_SERVICE_NAME
            value: rabbitmq
          - name: RABBITMQ_NODENAME
            value: rabbit@$(RABBITMQ-HERCULES).$(K8S_SERVICE_NAME).$(NAMESPACE-HERCULES-RPA).svc.cluster.local
          - name: K8S_HOSTNAME_SUFFIX
            value: {{ .Values.rabbitmq.address }}
      volumes:
        - name: definitions
          secret:
            secretName: {{ .Values.rabbitmq.secret.secretName }}
            items:
            - key: {{ .Values.rabbitmq.secret.definitionFile }}
              path: {{ .Values.rabbitmq.secret.definitionFile }}
        - name: rabbitmq
          secret:
            secretName: {{ .Values.rabbitmq.secret.secretName }}
            items:
            - key: {{ .Values.rabbitmq.secret.configurationFile }}
              path: {{ .Values.rabbitmq.secret.configurationFile }}
        - name: enabled-plugins
          secret:
            secretName: {{ .Values.rabbitmq.secret.secretName }}
            items:
            - key: {{ .Values.rabbitmq.secret.plugins }}
              path: {{ .Values.rabbitmq.secret.plugins }}