# Default values for rpa-plataform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secret:
  secretNamePostgres: secret-postgres
  usernamePostgresKey: username-postgres
  passwordPostgresKey: password-postgres
  secretNameRabbit: secret-rabbitmq
  usernameRabbitKey: username-rabbit
  passwordRabbitKey: password-rabbit
  secretNameCassandra: secret-cassandra
  usernameCassandraKey: username-cassandra
  passwordCassandraKey: password-cassandra
  
ingress:
  ingressClassName: "nginx"

rabbitmq:
  address : "rabbitmq.rpa-hercules.svc.cluster.local"

  replicaCount: 1

    # definitionFile: definitions.json
    # configurationFile: rabbitmq.conf
    # plugins: enabled_plugins

  image:
    repository: rabbitmq
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "3.8.27-management-alpine"

  resource:
    request:
      memory: "500Mi"
      cpu: "256m"
    limit:
      memory: "2Gi"
      cpu: "500m"

  service:
    type: NodePort
    http:
      port: 15672
      nodeport: 30659
    amqp:
      port: 5672
      nodeport: 30939
    dist:
      port: 25672
      nodeport: 31042

    
postgres:
  install: true
  address: "postgres.rpa-hercules.svc.cluster.local"
  
  replicaCount: 1

  image:
    repository: postgres
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "14-alpine"

  resource:
    request:
      memory: "1Gi"
      cpu: "250m"

    limit:
      memory: "1Gi"
      cpu: "500m" 

  service:
    type: ClusterIP
    tcp:
      port: 5432

  volumeClaim:
    storageClassName: nfs-client
    accessModes: ReadWriteOnce
    capacity:
      storage: 5Gi
    
cassandra:
  address : "cassandra.rpa-hercules.svc.cluster.local"
  replicaCount: 1

  image:
    repository: cassandra
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "3"

  resource:
    request:
      memory: "1Gi"
      cpu: "500m"

    limit:
      memory: "2Gi"
      cpu: "500m" 

  service:
    type: ClusterIP
    tcp:
      port: 9042

  volumeClaim:
    storageClassName: nfs-client
    accessModes: ReadWriteOnce
    capacity:
      storage: 5Gi

cdn:
  address : "cdn.rpa-hercules.svc.cluster.local"
  ingress_address : "rpa-cdn-desa.um.es"
  replicaCount: 1
  protocol: "https"

  image:
    repository: php
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "7.2-apache"

  resource:
    request:
      memory: "128Mi"
      cpu: "254m"

    limit:
      memory: "512Mi"
      cpu: "500m" 

  service:
    type: ClusterIP
    tcp:
      port: 80

  volumeClaim:
    storageClassName: nfs-client
    accessModes: ReadWriteOnce
    capacity:
      storage: 5Gi

    
backend:
  address: "app.rpa-hercules.svc.cluster.local"
  ingress_address: "rpa-api-desa.um.es"
  ingress_port: 80
  protocol: "https"
  
  secret:
    secretName: secret-backend
    fileJsonConfig: orchestratorK8s.json
    fileSqlConfig: insertSettings.sql

  image:
    repository: python
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "3.8-bullseye"

  resource:
    request:
      memory: "1Gi"
      cpu: "500m"

    limit:
      memory: "1Gi"
      cpu: "750m" 

  service:  
      type: ClusterIP
      flask:
        port: 5000

frontend:
  ingress_address: "rpa-desa.um.es"
  image:
    repository: node
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "16-alpine"

  resource:
    request:
      memory: "1Gi"
      cpu: "250m"

    limit:
      memory: "2Gi"
      cpu: "750m" 

  service:
    type: ClusterIP
    http:
      port: 8080
